### ISSUE TITLE
DatePicker component does not support input mask

### ISSUE THREAD

**Issue by SanderVanHullebusch** [a-ui/core_components_react#11]
I want to add an input mask to the DatePicker component to show the format dd/MM/yyyy.
Users have to manually fill in the slashes which is a but annoying.

I tried adding an input mask myself, but I get the following error (inputmask: __/__/__)

```
Unexpected Application Error!
Invalid time value
```

**Comment by TriangleJuice** [comment]
Hi Sander, because of accessibility reasons we don't support masks. A valid alternative is defining a description text, like: "Schrijf de datum zo: dd/mm/jjjj". This can also be used as the error text (in red) in case the user makes a mistake. More info in the docs: https://digitalehuisstijl.antwerpen.be/component/input-field
