### ISSUE TITLE
A11y for input components

### ISSUE THREAD

**Issue by SanderVanHullebusch** [a-ui/core_components_react#12]
For example a checkbox (https://github.com/a-ui/core_components_react/blob/development/packages/antwerp-ui/react-components/src/lib/atoms/checkbox/Checkbox.tsx)

Currently this listens to an onChange event. Can we also look at onKey events so that users can use their keyboard as much as possible?

**Comment by TriangleJuice** [comment]
Hi @SanderVanHullebusch, what exactly are you trying to accomplish? We have made all our components with accessibility in mind, so I'd like to reach out to see how we can improve them.

**Comment by SanderVanHullebusch** [comment]
I can't currently select a checkbox with my enter key. Is this something that is considered to be added to the library or best to add it ourselves?

**Comment by TriangleJuice** [comment]
Accessibility guidelines state that the Enter key is for submitting the form, while the space key is used to (un)check the checkbox. Also see: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role#keyboard_interactions

Is there some kind of acceptance criterium for this feature (because it is invalid)?
